version: '3.9'

networks:
  app-network-microservice:
    external: true

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.insecure=true
      - --entryPoints.web.address=:80
      - --providers.file.filename=/etc/traefik/dynamic.yaml
      - --providers.file.watch=true
      - --log.level=DEBUG
    ports:
      - "90:80"
      - "8100:8080"
    volumes:
      - ./dynamic.yaml:/etc/traefik/dynamic.yaml
    networks:
      - app-network-microservice
